name: flutterapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  youtube_player_iframe: ^2.2.2
  cached_network_image: ^3.1.0
#  webview_flutter: ^0.3.19+8
  chewie: ^1.3.0
  firebase_core: ^2.13.1
#  firebase_remote_config: ^0.5.0
  firebase_remote_config: ^4.2.2
  cloud_firestore: ^4.8.0
  firebase_analytics: ^10.4.2
  wakelock: ^0.6.1
  flutter_secure_storage: ^8.0.0
  video_player: 2.2.7
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_cache_manager: ^3.0.0
  pedantic: ^1.8.0+1
  audioplayers: ^0.20.1
  external_app_launcher: ^3.1.0
  flutter_local_notifications: ^10.0.0
  firebase_messaging: ^14.6.2
  share_plus: ^4.5.3
dev_dependencies:
  flutter_test:
      sdk: flutter
  flutter_launcher_icons: "^0.9.2"


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/images/drawer_header.jpg
    - lib/images/home_bg.jpg
    - lib/images/0.png
    - lib/images/1.png
    - lib/images/2.png
    - lib/images/3.png
    - assets/details.json
    - assets/details_copy.json
    - assets/address.json
    - lib/images/white_arrow.png
    - lib/images/hadees.png
    - lib/images/day.png
    - lib/images/lectures.png
    - lib/images/info.png
    - lib/images/kids.png
    - lib/images/tafseer.png
    - lib/images/nisaab.png
    - lib/images/dictionary.png
    - lib/images/khuddamLogo.jpeg
    - assets/audio_files.json
    - assets/hadees_details.json
    - assets/muntakhib_nisaab.json
    - assets/surah_list_reading.json
    - assets/verses/1.json
    - assets/verses/2.json
    - assets/verses/3.json
    - assets/verses/4.json
    - assets/verses/5.json
    - assets/verses/6.json
    - assets/verses/7.json
    - assets/verses/8.json
    - assets/verses/9.json
    - assets/verses/10.json
    - assets/verses/11.json
    - assets/verses/12.json
    - assets/verses/13.json
    - assets/verses/14.json
    - assets/verses/15.json
    - assets/verses/16.json
    - assets/verses/17.json
    - assets/verses/18.json
    - assets/verses/19.json
    - assets/verses/20.json
    - assets/verses/21.json
    - assets/verses/22.json
    - assets/verses/23.json
    - assets/verses/24.json
    - assets/verses/25.json
    - assets/verses/26.json
    - assets/verses/27.json
    - assets/verses/28.json
    - assets/verses/29.json
    - assets/verses/30.json
    - assets/verses/31.json
    - assets/verses/32.json
    - assets/verses/33.json
    - assets/verses/34.json
    - assets/verses/35.json
    - assets/verses/36.json
    - assets/verses/37.json
    - assets/verses/38.json
    - assets/verses/39.json
    - assets/verses/40.json
    - assets/verses/41.json
    - assets/verses/42.json
    - assets/verses/43.json
    - assets/verses/44.json
    - assets/verses/45.json
    - assets/verses/46.json
    - assets/verses/47.json
    - assets/verses/48.json
    - assets/verses/49.json
    - assets/verses/50.json
    - assets/verses/51.json
    - assets/verses/52.json
    - assets/verses/53.json
    - assets/verses/54.json
    - assets/verses/55.json
    - assets/verses/56.json
    - assets/verses/57.json
    - assets/verses/58.json
    - assets/verses/59.json
    - assets/verses/60.json
    - assets/verses/61.json
    - assets/verses/62.json
    - assets/verses/63.json
    - assets/verses/64.json
    - assets/verses/65.json
    - assets/verses/66.json
    - assets/verses/67.json
    - assets/verses/68.json
    - assets/verses/69.json
    - assets/verses/70.json
    - assets/verses/71.json
    - assets/verses/72.json
    - assets/verses/73.json
    - assets/verses/74.json
    - assets/verses/75.json
    - assets/verses/76.json
    - assets/verses/77.json
    - assets/verses/78.json
    - assets/verses/79.json
    - assets/verses/80.json
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: naskhregular
      fonts:
        - asset: assets/PDMS_Saleem_QuranFont.ttf
          style: normal

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
