
import 'package:flutter/material.dart';
import '../pages/homePageWithWidgets.dart';
import '../pages/surahListPage.dart';
import '../routes/drawer_routes.dart';
import 'package:flutter/services.dart';

import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_core/firebase_core.dart';

import '/firebase_options.dart'; // this file is generated by "flutterfire config" command
import 'package:firebase_messaging/firebase_messaging.dart';

import 'dart:async';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseMessaging messaging = FirebaseMessaging.instance;

  NotificationSettings settings = await messaging.requestPermission(
    alert: true,
    announcement: false,
    badge: true,
    carPlay: false,
    criticalAlert: false,
    provisional: false,
    sound: true,
  );

  print('User granted permission: ${settings.authorizationStatus}');

// Lisitnening to the background messages
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

// Listneing to the foreground messages
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseMessaging.onMessage.listen((RemoteMessage event) {
    print("message recieved");
    print(event.notification!.body);
  });
  FirebaseMessaging.onMessageOpenedApp.listen((message) {
    print('Message clicked!');
  });

  runApp(MyApp());
}

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
}

class SplashPage extends StatefulWidget {
  @override
  SplashPageState createState() => SplashPageState();
}

class SplashPageState extends State<SplashPage> {
// THIS FUNCTION WILL NAVIGATE FROM SPLASH SCREEN TO HOME SCREEN.    // USING NAVIGATOR CLASS.
//   FirebaseMessaging messaging;

  void navigationToNextPage() {
    Navigator.pushReplacementNamed(context, '/homePageWithWidgets');
  }

  startSplashScreenTimer() async {
    var _duration = new Duration(seconds: 3);
    return Timer(_duration, navigationToNextPage);
  }

  @override
  void initState() {
    super.initState();
    // FirebaseMessaging messaging = FirebaseMessaging.instance;
    // messaging.getToken().then((value) {
    //   print('Message is here: ${value}');
    // });
    startSplashScreenTimer();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    Size size = MediaQuery.of(context).size;

    return Column(
      children: [

        Container(
            color: Colors.white,
            alignment: Alignment.center,
            width: size.width,
            height: size.height * 0.92,
            child: Image.asset("lib/images/khuddamLogo.jpeg")),
        Container(
          color: Colors.white,
          alignment: Alignment.center,
          width: size.width,
          height: MediaQuery.of(context).size.height * 0.08,
          padding: EdgeInsets.only(left: 5, top: 0, right: 5, bottom: 0),
          child: Text("Designed & Developed by Saad Mansur for Sadaqah Jariyah",
              style: TextStyle(
                  backgroundColor: Colors.white,
                  fontWeight: FontWeight.bold,
                  fontSize: 12.0,
                  decoration: TextDecoration.none,
                  color: Colors.black)),
        ),
      ],
    );
  }
}

class MyApp extends StatelessWidget {
  static FirebaseAnalytics analytics = FirebaseAnalytics.instance;
  static FirebaseAnalyticsObserver observer =
      FirebaseAnalyticsObserver(analytics: analytics);

// This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'NavigationDrawer Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      navigatorObservers: <NavigatorObserver>[observer],
      home: SplashPage(),
      routes: {
        drawer_routes.home: (context) => homePageWithWidgets(),
//        drawer_routes.contact: (context) => YoutubePlayerDemo(title: 'Youtube Player'),
        drawer_routes.surahList: (context) => surahListPage(),
      },
    );
  }
}
